baseURL = "/"
disableAliases = true
enableRobotsTXT = true
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Bless Your Heart"
googleAnalytics = "UA-118254944-1"

[imaging]
anchor = "center"
quality = 90
[markup]
[markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[params]
description = "We are a mother daughter team specializing in farmhouse and french country decor and is passionate about making the vision for your home come true!"
facebook = "https://www.facebook.com/blessyourheartofal/"
instagram = "https://www.instagram.com/blessyourheartofal/"
pinterest = "https://www.pinterest.com/blessyourhearto/"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

