---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: file
  label: Image
  name: image
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true

