---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: file
  label: Image
  name: image
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: select
  name: author
  config:
    source:
      type: simple
    options:
    - Amy Hibbs
    - Melanie Evans
    - Lauren Gray
  label: Author
pages:
- content/journal/welcome-to-our-new-website.md
